---org.bukkit.inventory.ItemStack
---@class bukkit.ItemStack : bukkit.Translatable
---@field getType fun(): bukkit.Material
---@field setType fun(type: bukkit.Material)
---@field getAmount fun(): integer
---@field setAmount fun(amount: integer)
---@field getData fun(): java.Object? -- TODO
---@field setData fun(data: java.Object?) -- TODO
---@field getMaxStackSize fun(): integer
---@field isSimilar fun(itemStack: bukkit.ItemStack): boolean
---@field clone fun(): bukkit.ItemStack
---@field hasItemMeta fun(): boolean
---@field getItemMeta fun(): java.Object? -- TODO
---@field setItemMeta fun(meta: java.Object?) -- TODO
---@field getTranslationKey fun(): string

---@class bukkit.inventory.Inventory : java.Iterable<bukkit.ItemStack>
---@field getSize fun(): integer
---@field getMaxStackSize fun(): integer
---@field setMaxStackSize fun(v: integer)
---@field getItem fun(slot: integer): bukkit.ItemStack?
---@field setItem fun(slot: integer, itemStack: bukkit.ItemStack?)
---@field addItem fun(itemStacks: java.array<bukkit.ItemStack>): java.Map<integer, bukkit.ItemStack>
---@field removeItem fun(itemStacks: java.array<bukkit.ItemStack>): java.Map<integer, bukkit.ItemStack>
---@field removeItemAnySlot fun(itemStacks: java.array<bukkit.ItemStack>): java.Map<integer, bukkit.ItemStack>
---@field getContents fun(): java.array<bukkit.ItemStack|nil>
---@field setContents fun(v: java.array<bukkit.ItemStack|nil>)
---@field getStorageContents fun(): java.array<bukkit.ItemStack|nil>
---@field setStorageContents fun(v: java.array<bukkit.ItemStack|nil>)
---@field contains fun(id: bukkit.Material|bukkit.ItemStack, i: integer) -- TODO
---@field containsAtLeast fun(itemStack: bukkit.ItemStack, i: integer) -- TODO
---@field all function -- TODO
---@field first function -- TODO
---@field firstEmtpy fun(): integer
---@field isEmpty fun(): boolean
---@field remove fun(id: bukkit.Material|bukkit.ItemStack)
---@field clear fun(i?: integer)?
---@field close fun()
---@field getViewers fun(): java.List<bukkit.entity.HumanEntity>
---@field getType fun(): java.Object -- TODO
---@field getHolder fun(b?: boolean): bukkit.inventory.InventoryHolder? -- TODO
---@field iterator fun(i?: integer): java.Iterator<bukkit.ItemStack> -- TODO
---@field getLocation fun(): bukkit.Location?

---@class bukkit.inventory.InventoryHolder : java.Object
---@field getInventory fun(): bukkit.inventory.Inventory

-- TODO
---@class bukkit.inventory.InventoryView : java.Object
---@field getTopInventory fun(): bukkit.inventory.Inventory
---@field getBottomInventory fun(): bukkit.inventory.Inventory
---@field getPlayer fun(): bukkit.entity.HumanEntity
---@field getType fun(): java.Enum -- TODO
---@field getItem fun(slot: integer): bukkit.ItemStack?
---@field setItem fun(slot: integer, itemStack: bukkit.ItemStack?)
---@field getCursor fun(): bukkit.ItemStack
---@field setCursor fun(itemStack: bukkit.ItemStack?)
---@field getInventory fun(rawSlot: integer): bukkit.inventory.Inventory?
---@field convertSlot fun(rawSlot: integer): integer
---@field getSlotType fun(slot: integer): java.Object -- TODO
---@field open fun()
---@field close fun()
---@field countSlots fun(): integer
---@field setProperty fun(prop: java.Object, value: integer): boolean -- TODO
---@field getTitle fun(): string
---@field setTitle fun(title: string) -- Should not be used
---@field getMenuType fun(): java.Object? -- TODO

---@class bukkit.inventory.Merchant : java.Object

---org.bukkit.inventory.PlayerInventory
---@class bukkit.inventory.PlayerInventory : bukkit.inventory.Inventory
---@field getArmorContents fun(): java.array<bukkit.ItemStack>
---@field setArmorContents fun(items: java.array<bukkit.ItemStack>?)
---@field getExtraContents fun(): java.array<bukkit.ItemStack>
---@field setExtraContents fun(items: java.array<bukkit.ItemStack>?)
---@field getHelmet fun(): bukkit.ItemStack?
---@field setHelmet fun(itemStack: bukkit.ItemStack)
---@field getChestplate fun(): bukkit.ItemStack?
---@field setChestplate fun(itemStack: bukkit.ItemStack)
---@field getLeggings fun(): bukkit.ItemStack?
---@field setLeggings fun(itemStack: bukkit.ItemStack)
---@field getBoots fun(): bukkit.ItemStack?
---@field setBoots fun(itemStack: bukkit.ItemStack)
---@field getItem fun(slot: integer|bukkit.inventory.EquipmentSlot): bukkit.ItemStack?
---@field setItem fun(slot: integer|bukkit.inventory.EquipmentSlot, itemStack: bukkit.ItemStack)
---@field getItemInMainHand fun(): bukkit.ItemStack
---@field setItemInMainHand fun(itemStack: bukkit.ItemStack?)
---@field getItemInOffHand fun(): bukkit.ItemStack
---@field setItemInOffHand fun(itemStack: bukkit.ItemStack?)
---@field getHeldItemSlot fun(): integer
---@field setHeltItemSlot fun(slot: integer)
---@field getHolder fun(): bukkit.entity.HumanEntity

---@alias bukkit.inventory.EquipmentSlot* string
---| "HAND"
---| "OFF_HAND"
---| "FEET"
---| "LEGS"
---| "CHEST"
---| "HEAD"
---| "BODY"

---@class bukkit.inventory.EquipmentSlot : java.Enum
---@field getGroup fun(): bukkit.inventory.EquipmentSlotGroup

---@alias bukkit.inventory.EquipmentSlotGroup* string
---| "ANY"
---| "MAINHAND"
---| "OFFHAND"
---| "HAND"
---| "FEET"
---| "LEGS"
---| "CHEST"
---| "HEAD"
---| "ARMOR"

---@class bukkit.inventory.EquipmentSlotGroup : java.Predicate<bukkit.inventory.EquipmentSlot>
---@field test fun(slot: bukkit.inventory.EquipmentSlot): boolean
