---@alias bukkit.Particle* string
---| "minecraft:poof"
---| "minecraft:explosion"
---| "minecraft:explosion_emitter"
---| "minecraft:firework"
---| "minecraft:bubble"
---| "minecraft:splash"
---| "minecraft:fishing"
---| "minecraft:underwater"
---| "minecraft:crit"
---| "minecraft:enchanted_hit"
---| "minecraft:smoke"
---| "minecraft:large_smoke"
---| "minecraft:effect"
---| "minecraft:instant_effect"
---| "minecraft:entity_effect" -- Color
---| "minecraft:witch"
---| "minecraft:dripping_water"
---| "minecraft:dripping_lava"
---| "minecraft:angry_villager"
---| "minecraft:happy_villager"
---| "minecraft:mycelium"
---| "minecraft:note"
---| "minecraft:portal"
---| "minecraft:enchant"
---| "minecraft:flame"
---| "minecraft:lava"
---| "minecraft:cloud"
---| "minecraft:dust" -- Particle.DustOptions
---| "minecraft:item_snowball"
---| "minecraft:item_slime"
---| "minecraft:heart"
---| "minecraft:item" -- ItemStack
---| "minecraft:block" -- BlockData
---| "minecraft:rain"
---| "minecraft:elder_guardian"
---| "minecraft:dragon_breath"
---| "minecraft:end_rod"
---| "minecraft:damage_indicator"
---| "minecraft:sweep_attack"
---| "minecraft:falling_dust" -- BlockData
---| "minecraft:totem_of_undying"
---| "minecraft:spit"
---| "minecraft:squid_ink"
---| "minecraft:bubble_pop"
---| "minecraft:current_down"
---| "minecraft:bubble_column_up"
---| "minecraft:nautilus"
---| "minecraft:dolphin"
---| "minecraft:sneeze"
---| "minecraft:campfire_cosy_smoke"
---| "minecraft:campfire_signal_smoke"
---| "minecraft:composter"
---| "minecraft:flash"
---| "minecraft:falling_lava"
---| "minecraft:landing_lava"
---| "minecraft:falling_water"
---| "minecraft:dripping_honey"
---| "minecraft:falling_honey"
---| "minecraft:landing_honey"
---| "minecraft:falling_nectar"
---| "minecraft:soul_fire_flame"
---| "minecraft:ash"
---| "minecraft:crimson_spore"
---| "minecraft:warped_spore"
---| "minecraft:soul"
---| "minecraft:dripping_obsidian_tear"
---| "minecraft:falling_obsidian_tear"
---| "minecraft:landing_obsidian_tear"
---| "minecraft:reverse_portal"
---| "minecraft:white_ash"
---| "minecraft:dust_color_transition" -- DustTransition
---| "minecraft:vibration" -- Vibration
---| "minecraft:falling_spore_blossom"
---| "minecraft:spore_blossom_air"
---| "minecraft:small_flame"
---| "minecraft:snowflake"
---| "minecraft:dripping_dripstone_lava"
---| "minecraft:falling_dripstone_lava"
---| "minecraft:dripping_dripstone_water"
---| "minecraft:falling_dripstone_water"
---| "minecraft:glow_squid_ink"
---| "minecraft:glow"
---| "minecraft:wax_on"
---| "minecraft:wax_off"
---| "minecraft:electric_spark"
---| "minecraft:scrape"
---| "minecraft:sonic_boom"
---| "minecraft:sculk_soul"
---| "minecraft:sculk_charge" -- Float
---| "minecraft:sculk_charge_pop"
---| "minecraft:shriek" -- Integer
---| "minecraft:cherry_leaves"
---| "minecraft:pale_oak_leaves"
---| "minecraft:tinted_leaves" -- Color
---| "minecraft:egg_crack"
---| "minecraft:dust_plume"
---| "minecraft:white_smoke"
---| "minecraft:gust"
---| "minecraft:small_gust"
---| "minecraft:gust_emitter_large"
---| "minecraft:gust_emitter_small"
---| "minecraft:trial_spawner_detection"
---| "minecraft:trial_spawner_detection_ominous"
---| "minecraft:vault_connection"
---| "minecraft:infested"
---| "minecraft:item_cobweb"
---| "minecraft:dust_pillar" -- BlockData
---| "minecraft:block_crumble" -- BlockData
---| "minecraft:firefly"
---| "minecraft:trail" -- Trail
---| "minecraft:ominous_spawning"
---| "minecraft:raid_omen"
---| "minecraft:trial_omen"
---| "minecraft:block_marker" -- BlockData

---@class bukkit.Particle : java.Enum, bukkit.Keyed
---@field getDataType fun(): java.Class
---@field getKey fun(): bukkit.NamespacedKey

---@class bukkit.Particle.DustOptions : java.Object

---@class bukkit.Particle.DustTransition : bukkit.Particle.DustOptions

---@class bukkit.Particle.Trail : java.Object
