---@alias bukkit.ParticleLike bukkit.NamespacedKeyLike|bukkit.Particle*|bukkit.Particle

---@alias bukkit.Particle* string
---| "poof"
---| "explosion"
---| "explosion_emitter"
---| "firework"
---| "bubble"
---| "splash"
---| "fishing"
---| "underwater"
---| "crit"
---| "enchanted_hit"
---| "smoke"
---| "large_smoke"
---| "effect"
---| "instant_effect"
---| "entity_effect" -- Color
---| "witch"
---| "dripping_water"
---| "dripping_lava"
---| "angry_villager"
---| "happy_villager"
---| "mycelium"
---| "note"
---| "portal"
---| "enchant"
---| "flame"
---| "lava"
---| "cloud"
---| "dust" -- Particle.DustOptions
---| "item_snowball"
---| "item_slime"
---| "heart"
---| "item" -- ItemStack
---| "block" -- BlockData
---| "rain"
---| "elder_guardian"
---| "dragon_breath"
---| "end_rod"
---| "damage_indicator"
---| "sweep_attack"
---| "falling_dust" -- BlockData
---| "totem_of_undying"
---| "spit"
---| "squid_ink"
---| "bubble_pop"
---| "current_down"
---| "bubble_column_up"
---| "nautilus"
---| "dolphin"
---| "sneeze"
---| "campfire_cosy_smoke"
---| "campfire_signal_smoke"
---| "composter"
---| "flash"
---| "falling_lava"
---| "landing_lava"
---| "falling_water"
---| "dripping_honey"
---| "falling_honey"
---| "landing_honey"
---| "falling_nectar"
---| "soul_fire_flame"
---| "ash"
---| "crimson_spore"
---| "warped_spore"
---| "soul"
---| "dripping_obsidian_tear"
---| "falling_obsidian_tear"
---| "landing_obsidian_tear"
---| "reverse_portal"
---| "white_ash"
---| "dust_color_transition" -- DustTransition
---| "vibration" -- Vibration
---| "falling_spore_blossom"
---| "spore_blossom_air"
---| "small_flame"
---| "snowflake"
---| "dripping_dripstone_lava"
---| "falling_dripstone_lava"
---| "dripping_dripstone_water"
---| "falling_dripstone_water"
---| "glow_squid_ink"
---| "glow"
---| "wax_on"
---| "wax_off"
---| "electric_spark"
---| "scrape"
---| "sonic_boom"
---| "sculk_soul"
---| "sculk_charge" -- Float
---| "sculk_charge_pop"
---| "shriek" -- Integer
---| "cherry_leaves"
---| "pale_oak_leaves"
---| "tinted_leaves" -- Color
---| "egg_crack"
---| "dust_plume"
---| "white_smoke"
---| "gust"
---| "small_gust"
---| "gust_emitter_large"
---| "gust_emitter_small"
---| "trial_spawner_detection"
---| "trial_spawner_detection_ominous"
---| "vault_connection"
---| "infested"
---| "item_cobweb"
---| "dust_pillar" -- BlockData
---| "block_crumble" -- BlockData
---| "firefly"
---| "trail" -- Trail
---| "ominous_spawning"
---| "raid_omen"
---| "trial_omen"
---| "block_marker" -- BlockData

---@class bukkit.Particle : java.Enum, bukkit.Keyed
---@field getDataType fun(): java.Class
---@field getKey fun(): bukkit.NamespacedKey

---@class bukkit.Particle.DustOptions : java.Object

---@class bukkit.Particle.DustTransition : bukkit.Particle.DustOptions

---@class bukkit.Particle.Trail : java.Object
